# Корутини

Корутина — це функція, яка може бути призупинена під час виконання, щоб дозволити виконання інших задач, і потім відновлена з того ж місця. Це дозволяє ефективно виконувати асинхронні операції, такі як введення-виведення, не блокуючи основний потік виконання. Корутину можна визначити за допомогою виразу `async def`. Виклик такої функції створює об'єкт корутини.

## Об'єкт корутини

Об'єкт корутини — це спеціальний об'єкт, який представляє асинхронну операцію і може бути очікуваний (`await`) або запущений у контексті подійного циклу (наприклад, за допомогою `asyncio`). Об'єкти корутин мають кілька методів та властивостей для керування їхнім станом:

-   `.await_()`: Використовується для програмного очікування корутини (еквівалент ключового слова `await`).
-   `.send(value)`: Відновлює виконання та передає значення в корутину.
-   `.throw(exc_type, exc_value=None, traceback=None)`: Зупиняє виконання корутини і викликає виключення в її контексті.
-   `.close()`: Завершує корутину.

## Стани корутин

-   Pending (очікування): Створена, але ще не запущена. Наприклад, після виклику асинхронної функції, але до її запуску.
-   Running (виконання): Активно виконується в даний момент.
-   Suspended (призупинено): Тимчасово призупинена, наприклад, при очікуванні завершення I/O операції за допомогою `await`.
-   Completed (завершено): Успішно завершена та повернула результат.
-   Failed (не вдалося): Завершена з помилкою, викинуто виключення.

## Приклад використання

```py
import asyncio
import aiohttp

async def fetch_data():
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get('https://api.example.com/data') as response:
                data = await response.json()
                print(data)
    except Exception as e:
        print(f'Error fetching data: {e}')

async def main():
    await fetch_data()

asyncio.run(main())
```
